name: Refresh Brewery Data

on:
  schedule:
    # Runs at 04:00 UTC every Wednesday
    - cron: "0 4 * * 3"
  workflow_dispatch:

jobs:
  refresh-brewery-data:
    name: Refresh Brewery Data
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate & Publish Brewery JSON
        env:
          # Retrieve Github Secrets
          GIST_ID: ${{ secrets.GIST_ID }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        run: |
          python src/main.py
          echo "### 🍺 Brewery Data Updated Successfully" >> $GITHUB_STEP_SUMMARY
